Repository Qiskit/qiskit-ibmq-provider, pull requests merged in 2020-08, with the labels that each got.

#731 Allow querying for backed reservations
  qiskit/providers/ibmq/api/clients/account.py
  qiskit/providers/ibmq/api/rest/backend.py
  qiskit/providers/ibmq/api/rest/root.py
  qiskit/providers/ibmq/api/session.py
  qiskit/providers/ibmq/backendreservation.py
  qiskit/providers/ibmq/ibmqbackend.py
  qiskit/providers/ibmq/ibmqbackendservice.py
  qiskit/providers/ibmq/utils/backend.py
  releasenotes/notes/backend-reservation-c445db6d8de5a896.yaml
  test/ibmq/test_ibmq_backend.py
Labels: Changelog: New Feature

#732 Take reservations into account in least_busy
  qiskit/providers/ibmq/__init__.py
  qiskit/providers/ibmq/backendreservation.py
  releasenotes/notes/least-busy-reservations-156f81daf69c5e56.yaml
  test/ibmq/test_filter_backends.py
Labels: Changelog: New Feature

#738 Suppress timeout error from waiting for old job
  qiskit/providers/ibmq/managed/managedjob.py
  releasenotes/notes/jm-timeout-error-e166adbbaed8a0a6.yaml
  test/fake_account_client.py
  test/ibmq/test_ibmq_jobmanager.py
Labels: Changelog: Bugfix, backport potential

#740 Fix module name in ibmq apidoc index
  docs/apidocs/ibmq-provider.rst
Labels: backport potential
