Repository Qiskit/qiskit-ibmq-provider, pull requests merged in 2020-10, with the labels that each got.

#765 Experiment service
  qiskit/providers/ibmq/accountprovider.py
  qiskit/providers/ibmq/api/clients/auth.py
  qiskit/providers/ibmq/api/clients/experiment.py
  qiskit/providers/ibmq/api/exceptions.py
  qiskit/providers/ibmq/api/rest/analysis_result.py
  qiskit/providers/ibmq/api/rest/experiment.py
  qiskit/providers/ibmq/api/rest/root.py
  qiskit/providers/ibmq/api/rest/utils/data_mapper.py
  qiskit/providers/ibmq/api/session.py
  qiskit/providers/ibmq/credentials/credentials.py
  qiskit/providers/ibmq/exceptions.py
  qiskit/providers/ibmq/experiment/__init__.py
  qiskit/providers/ibmq/experiment/analysis_result.py
  qiskit/providers/ibmq/experiment/constants.py
  qiskit/providers/ibmq/experiment/exceptions.py
  qiskit/providers/ibmq/experiment/experiment.py
  qiskit/providers/ibmq/experiment/experimentservice.py
  qiskit/providers/ibmq/experiment/utils.py
  qiskit/providers/ibmq/utils/converters.py
  releasenotes/notes/experiment-service-3459f8e3c9f8c1c8.yaml
  setup.py
  test/ibmq/test_experiment.py
Labels: Changelog: New Feature

#776 Fix provider not found in test case
  test/decorators.py
  test/ibmq/test_experiment.py
Labels: backport potential

#779 Drop support for Python 3.5
  .travis.yml
  Makefile
  azure-pipelines.yml
  qiskit/providers/ibmq/api/clients/account.py
  qiskit/providers/ibmq/api/clients/auth.py
  qiskit/providers/ibmq/api/clients/websocket.py
  qiskit/providers/ibmq/api/rest/backend.py
  qiskit/providers/ibmq/backendjoblimit.py
  qiskit/providers/ibmq/backendreservation.py
  qiskit/providers/ibmq/ibmqbackendservice.py
  qiskit/providers/ibmq/job/ibmqjob.py
  qiskit/providers/ibmq/job/queueinfo.py
  qiskit/providers/ibmq/managed/managedresults.py
  qiskit/providers/ibmq/managed/utils.py
  qiskit/providers/ibmq/random/baserandomservice.py
  qiskit/providers/ibmq/random/cqcextractor.py
  qiskit/providers/ibmq/random/ibmqrandomservice.py
  qiskit/providers/ibmq/version.py
  releasenotes/notes/drop-py35-0eec8b799e9ae407.yaml
  releasenotes/notes/websockets-8-b02a2cdc133c2a25.yaml
  requirements-dev.txt
  requirements.txt
  setup.py
  test/ibmq/websocket/websocket_server.py
  tox.ini
Labels: Changelog: Removal

#788 Handle new list API response body format
  qiskit/providers/ibmq/api/clients/experiment.py
  qiskit/providers/ibmq/api/rest/root.py
Labels: Changelog: Bugfix

#790 Add links to schema
  qiskit/providers/ibmq/ibmqbackend.py
Labels: type: documentation
