Repository Qiskit/qiskit-ibmq-provider, pull requests merged in 2020-12, with the labels that each got.

#821 Add min_num_qubits as a backends filter
  qiskit/providers/ibmq/ibmqbackendservice.py
  releasenotes/notes/backend-filter-min-qubits-05a96da6f5e08487.yaml
  test/decorators.py
  test/ibmq/test_filter_backends.py
Labels: Changelog: New Feature

#829 Expose Experiment visibility and owner attributes
  qiskit/providers/ibmq/experiment/constants.py
  qiskit/providers/ibmq/experiment/experiment.py
  qiskit/providers/ibmq/experiment/experimentservice.py
  releasenotes/notes/experiment-share-level-owner-c27323240f27d5fe.yaml
  test/ibmq/test_experiment.py
Labels: Changelog: New Feature

#817 Use v2 provider interface
  Makefile
  qiskit/providers/ibmq/__init__.py
  qiskit/providers/ibmq/accountprovider.py
  qiskit/providers/ibmq/ibmqbackend.py
  qiskit/providers/ibmq/job/ibmqjob.py
  qiskit/providers/ibmq/utils/json_decoder.py
  releasenotes/notes/backend-run-circuits-ad446ca9b56209b9.yaml
  requirements.txt
  setup.cfg
  setup.py
  test/ibmq/test_basic_server_paths.py
  test/ibmq/test_ibmq_backend.py
  test/ibmq/test_ibmq_integration.py
  test/ibmq/test_ibmq_job.py
  test/ibmq/test_ibmq_job_attributes.py
  test/ibmq/test_ibmq_provider.py
  test/ibmq/test_ibmq_qasm_simulator.py
  test/ibmq/test_jupyter.py
  test/ibmq/test_proxies.py
  test/ibmq/test_serialization.py
  test/ibmq/websocket/test_websocket_integration.py
  test/utils.py
Labels: Changelog: Deprecation, Changelog: New Feature

#822 Rename provider.backends to provider.backend
  docs/tutorials/1_the_ibmq_account.ipynb
  qiskit/providers/ibmq/accountprovider.py
  qiskit/providers/ibmq/ibmqbackend.py
  qiskit/providers/ibmq/ibmqbackendservice.py
  qiskit/providers/ibmq/managed/managedjobset.py
  releasenotes/notes/backends-to-backend-76f460795926ed22.yaml
  test/ibmq/test_basic_server_paths.py
  test/ibmq/test_ibmq_backend.py
  test/ibmq/test_ibmq_job.py
  test/ibmq/test_ibmq_job_attributes.py
  test/ibmq/test_ibmq_jobmanager.py
  test/ibmq/test_ibmq_provider.py
Labels: Changelog: API Change

#841 Remove obsolete functions
  qiskit/providers/ibmq/credentials/__init__.py
  qiskit/providers/ibmq/credentials/credentials.py
  qiskit/providers/ibmq/credentials/qconfig.py
  qiskit/providers/ibmq/ibmqbackend.py
  qiskit/providers/ibmq/ibmqbackendservice.py
  qiskit/providers/ibmq/ibmqfactory.py
  qiskit/providers/ibmq/job/ibmqjob.py
  releasenotes/notes/deprecated-removed-135995c7a8a87c04.yaml
  test/decorators.py
  test/ibmq/test_ibmq_factory.py
  test/ibmq/test_ibmq_job.py
  test/ibmq/test_registration.py
Labels: Changelog: Removal

#845 Stop hard coding gate names in backend monitor
  docs/tutorials/1_the_ibmq_account.ipynb
  qiskit/providers/ibmq/ibmqbackendservice.py
  qiskit/providers/ibmq/jupyter/qubits_widget.py
  releasenotes/notes/jupyter-gates-c0daee55cd6625d0.yaml
  requirements-dev.txt
  setup.py
Labels: Changelog: Bugfix, backport potential
