Repository Qiskit/qiskit-ibmq-provider, pull requests merged in 2020-09, with the labels that each got.

#754 Add random number generator service
  docs/apidocs/ibmq-provider.rst
  docs/apidocs/ibmq_random.rst
  qiskit/providers/ibmq/accountprovider.py
  qiskit/providers/ibmq/api/clients/random.py
  qiskit/providers/ibmq/api/rest/job.py
  qiskit/providers/ibmq/api/rest/random.py
  qiskit/providers/ibmq/api/session.py
  qiskit/providers/ibmq/credentials/credentials.py
  qiskit/providers/ibmq/ibmqfactory.py
  qiskit/providers/ibmq/random/__init__.py
  qiskit/providers/ibmq/random/baserandomservice.py
  qiskit/providers/ibmq/random/cqcextractor.py
  qiskit/providers/ibmq/random/ibmqrandomservice.py
  qiskit/providers/ibmq/random/utils.py
  releasenotes/notes/random_service-0173249bd082affd.yaml
  setup.py
  test/ibmq/test_random.py
Labels: Changelog: New Feature

#750 Drop support for Python 3.5
  .travis.yml
  azure-pipelines.yml
  releasenotes/notes/drop-py35-0eec8b799e9ae407.yaml
  requirements-dev.txt
  setup.py
  tox.ini
Labels: Changelog: Removal

#761 Fix session headers and error response
  qiskit/providers/ibmq/api/rest/job.py
  qiskit/providers/ibmq/api/session.py
Labels: backport potential

#733 Add reservation info to Jupyter widgets
  qiskit/providers/ibmq/jupyter/config_widget.py
  qiskit/providers/ibmq/jupyter/dashboard/backend_update.py
  qiskit/providers/ibmq/jupyter/dashboard/backend_widget.py
  qiskit/providers/ibmq/jupyter/dashboard/constants.py
  qiskit/providers/ibmq/jupyter/utils.py
  releasenotes/notes/jupyter-reservation-f215cce5f6972c93.yaml
Labels: Changelog: New Feature

#766 Asynchronous CQC extractors
  azure-pipelines.yml
  qiskit/providers/ibmq/api/clients/random.py
  qiskit/providers/ibmq/api/rest/random.py
  qiskit/providers/ibmq/ibmqbackend.py
  qiskit/providers/ibmq/job/ibmqjob.py
  qiskit/providers/ibmq/job/queueinfo.py
  qiskit/providers/ibmq/job/utils.py
  qiskit/providers/ibmq/random/__init__.py
  qiskit/providers/ibmq/random/cqcextractor.py
  qiskit/providers/ibmq/random/cqcextractorjob.py
  qiskit/providers/ibmq/random/ibmqrandomservice.py
  qiskit/providers/ibmq/utils/utils.py
  releasenotes/notes/async-extractor-23725ceaa94a3537.yaml
  requirements-dev.txt
  test/ibmq/test_ibmq_job.py
  test/ibmq/test_random.py
Labels: Changelog: New Feature
