Repository Qiskit/qiskit-ibmq-provider, pull requests merged in 2021-07, with the labels that each got.

#980 Add support for viewing error message if runtime job failed
  qiskit/providers/ibmq/runtime/constants.py
  qiskit/providers/ibmq/runtime/runtime_job.py
  releasenotes/notes/added-runtime-job-error-message-95eedc250ba94e4c.yaml
  test/ibmq/runtime/fake_runtime_client.py
  test/ibmq/runtime/test_runtime.py
  test/ibmq/runtime/test_runtime_integration.py
Labels: Changelog: New Feature

#1007 Remove validate_qobj parameter from IBMQBackend.run()
  qiskit/providers/ibmq/ibmqbackend.py
  releasenotes/notes/short-description-string-57a52d3158cb3abd.yaml
  test/ibmq/test_ibmq_job.py
  test/ibmq/test_ibmq_provider.py
  test/ibmq/test_ibmq_qasm_simulator.py
  test/ibmq/websocket/test_websocket_integration.py
Labels: Changelog: Removal

#1017 Convert callable to None in RuntimeEncoder
  qiskit/providers/ibmq/runtime/utils.py
  releasenotes/notes/runtime-callable-2975b737e8fa2542.yaml
  test/ibmq/runtime/test_runtime.py
Labels: Changelog: API Change

#1032 Allow setting experiment service preferences
  qiskit/providers/ibmq/credentials/__init__.py
  qiskit/providers/ibmq/credentials/configrc.py
  qiskit/providers/ibmq/credentials/credentials.py
  qiskit/providers/ibmq/credentials/environ.py
  qiskit/providers/ibmq/experiment/ibm_experiment_service.py
  qiskit/providers/ibmq/ibmqfactory.py
  qiskit/providers/ibmq/runtime/runtime_program.py
  releasenotes/notes/added-experiment-service-options-f147c7b20262a332.yaml
  test/contextmanagers.py
  test/ibmq/experiment/test_experiment.py
  test/ibmq/experiment/test_experiment_data_integration.py
  test/ibmq/experiment/test_experiment_server_integration.py
  test/ibmq/test_registration.py
Labels: Changelog: New Feature
