Repository Qiskit/qiskit-ibmq-provider, pull requests merged in 2021-06, with the labels that each got.

#947 Support proxy for runtime result streaming
  .github/workflows/pr.yml
  qiskit/providers/ibmq/api/clients/runtime_ws.py
  qiskit/providers/ibmq/runtime/ibm_runtime_service.py
  qiskit/providers/ibmq/runtime/runtime_job.py
  releasenotes/notes/runtime-ws-4e81556d1905228f.yaml
  requirements.txt
  setup.py
  test/ibmq/runtime/test_runtime.py
  test/ibmq/runtime/test_runtime_integration.py
  test/ibmq/runtime/test_runtime_ws.py
Labels: Changelog: Bugfix

#949 Allow retrieving runtime job logs
  qiskit/providers/ibmq/api/clients/runtime.py
  qiskit/providers/ibmq/api/rest/runtime.py
  qiskit/providers/ibmq/runtime/runtime_job.py
  releasenotes/notes/runtime-logs-256c79f2fd071eae.yaml
  test/ibmq/runtime/test_runtime_integration.py
Labels: Changelog: New Feature

#957 Add input_allowed backend filter
  qiskit/providers/ibmq/ibmqbackendservice.py
  releasenotes/notes/runtime_backend-fe2dc3d6054eee41.yaml
  test/ibmq/test_filter_backends.py
Labels: Changelog: New Feature

#950 Added ProviderRequestParams option for run()
  qiskit/providers/ibmq/__init__.py
  qiskit/providers/ibmq/runtime/__init__.py
  qiskit/providers/ibmq/runtime/ibm_runtime_service.py
  qiskit/providers/ibmq/runtime/runtime_program.py
  releasenotes/notes/added-runtime-params-class-a458e64bea4ec8f6.yaml
  test/ibmq/runtime/test_runtime.py
Labels: Changelog: API Change, Changelog: New Feature

#970 remove job share level logic w/o breaking API
  qiskit/providers/ibmq/api/clients/account.py
  qiskit/providers/ibmq/api/rest/account.py
  qiskit/providers/ibmq/ibmqbackend.py
  qiskit/providers/ibmq/job/ibmqjob.py
  qiskit/providers/ibmq/managed/ibmqjobmanager.py
  qiskit/providers/ibmq/managed/managedjob.py
  qiskit/providers/ibmq/managed/managedjobset.py
  releasenotes/notes/unsupported-job-share-level-bfb3a505393f1981.yaml
  test/fake_account_client.py
  test/http_server.py
  test/ibmq/test_experiment.py
  test/ibmq/test_ibmq_job_attributes.py
  test/ibmq/test_ibmq_jobmanager.py
Labels: Changelog: Removal

#967 added-runtime-program-visibility
  qiskit/providers/ibmq/api/clients/runtime.py
  qiskit/providers/ibmq/api/rest/runtime.py
  qiskit/providers/ibmq/runtime/ibm_runtime_service.py
  qiskit/providers/ibmq/runtime/runtime_program.py
  releasenotes/notes/added-runtime-visibility-db8da3f1df4507ca.yaml
  test/ibmq/runtime/fake_runtime_client.py
  test/ibmq/runtime/test_runtime_integration.py
Labels: Changelog: New Feature

#979 add pending parameter to filter jobs
  qiskit/providers/ibmq/api/clients/runtime.py
  qiskit/providers/ibmq/api/rest/runtime.py
  qiskit/providers/ibmq/runtime/ibm_runtime_service.py
  releasenotes/notes/get-jobs-filter-by-pending-f93b3adce159a34d.yaml
  test/ibmq/runtime/fake_runtime_client.py
  test/ibmq/runtime/test_runtime.py
  test/ibmq/runtime/test_runtime_integration.py
Labels: Changelog: New Feature

#982 Always try using PulseBackendConfiguration first
  qiskit/providers/ibmq/accountprovider.py
  releasenotes/notes/pulse-config-3368ff94333e7278.yaml
Labels: Changelog: API Change
